### ISSUE TITLE
Android gradle version

### ISSUE THREAD

**Issue by allforabit** [mozilla/rust-android-gradle#53]
Apologies I might be missing something obvious as I'm relatively new to Android development. I'm just wondering if this plugin requires a particular android gradle plugin to be used in the app? I'm getting the following error on attempting to install this plugin:

```Could not find com.android.tools.build:gradle:3.1.2```

My project is using the following version:

```com.android.tools.build:gradle:4.1.3```

Thanks, any pointers greatly appreciated!

**Comment by ncalexan** [comment]
Hi @allforabit!  The plugin requires version 3.1.2 at this time.  I've not touched it for ages -- probably about 2 years -- and just recently did a few small things to help a few consumers.  That got me thinking about how to support multiple versions of things, so I'm going to change this issue to be about that.

We'd very much like to support many (all?) versions of the Android-Gradle plugin (henceforth, AGP).  But that will be tricky; here's my understanding.  AGP and Gradle together put various limitations on the Kotlin version, although I think that doesn't matter too much for a plugin, since we're shipping JVM byte code.  AGP itself requires [specific Gradle versions](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle), so we don't really have a "Gradle version" vs "AGP version" matrix, we have a list of compatible version pairs.  I believe that there are non-trivial techniques to [accommodate multiple Gradle versions](https://discuss.gradle.org/t/gradle-plugin-supporting-multiple-version-of-gradle/32809) but I am not even close to expert in this area.  I think that we're supposed to declare AGP as a compile-time dependency so that we transparently accept whatever the consumer's project declares, and then do reflection and other things to access various legacy dependencies.  I don't know, in practice, how well that can work.

So let me leave this ticket as a "we would like to do better" placeholder that I have no real plan to address.  I will note that I bumped a bunch of dependencies and am pretty sure that things still work; I will push that to a branch so that others can experiment with it.  I imagine the community as a whole would rather have a plugin that assumes a modern version of AGP than the existing plugin (version 0.8.5) which assumes an ancient version, so hopefully we can modernize sometime soon.  I would love for knowledgeable folks to make this better.

**Comment by ncalexan** [comment]
A few further notes on this:

1.  https://github.com/gradle/android-cache-fix-gradle-plugin shows how to handle multiple AGP versions, including testing.  Amazing work.
2.  It's worth noting that gradle/android-cache-fix-gradle-plugin depends on the _earliest_ version of AGP that they support.  I don't understand why this is the case.
3.  By making the AGP dependency `compileOnly`, we should address the immediate issue.  The only AGP difference I see is that `defaultConfig.minSdkVersion` became optional at some point.  Presumably we can use reflection to access this?  Or maybe it doesn't actually change at the JVM level?

**Comment by allforabit** [comment]
Hi @ncalexan thanks very much for getting back to me. Yes that's the reason I was unsure about the version was because it looked like it was updated very recently. Gradle is something that I want to try and understand more and will look into it in more detail and try help out if I can. It looks like a fairly complex thing though so it might be a while! 

I'm not sure if this is any help but I had some luck with https://github.com/bbqsrc/cargo-ndk which builds the `so` files for you and you just put them in the `jniLibs` folder. It's not quite as seamless as a gradle plugin but it's good enough for my purposes for now.

**Comment by ncalexan** [comment]
> Hi @ncalexan thanks very much for getting back to me. Yes that's the reason I was unsure about the version was because it looked like it was updated very recently. Gradle is something that I want to try and understand more and will look into it in more detail and try help out if I can. It looks like a fairly complex thing though so it might be a while!

Roger that.  Any help is appreciated, but don't feel obligated: so little time and so much to be done.

> I'm not sure if this is any help but I had some luck with https://github.com/bbqsrc/cargo-ndk which builds the `so` files for you and you just put them in the `jniLibs` folder. It's not quite as seamless as a gradle plugin but it's good enough for my purposes for now.

You should be aware of our sister plugin, then: https://github.com/willir/cargo-ndk-android-gradle.  I'm a big fan of their approach, and would love to [harmonize and eventually merge](https://github.com/mozilla/rust-android-gradle/issues/40).

**Comment by allforabit** [comment]
Oh wow that's amazing thank you very much, have starred that project too! Great to hear that you are looking at harmonizing with them. Hopefully there'll be more interest in this area now that Google are embracing Rust on Android.

**Comment by perqin** [comment]
Hi @ncalexan I would like to know the progress of this plugin accommodating recent AGP releases. I'm facing the same issue, and maybe I could help make this plugin work with AGP.

**Comment by ncalexan** [comment]
> Hi @ncalexan I would like to know the progress of this plugin accommodating recent AGP releases. I'm facing the same issue, and maybe I could help make this plugin work with AGP.

@perqin I would love some help with this.  I have some WIP that's quite close for working with multiple AGP releases and testing against multiple AGP + Gradle versions so that we can be confident in what we're doing.  Give me a day or two to push something up and you can help test it and extend it to the versions you care about?

**Comment by perqin** [comment]
@ncalexan That's great! Feel free to notify me whenever your work is pushed up and I'll give it a try.

**Comment by ncalexan** [comment]
> @ncalexan That's great! Feel free to notify me whenever your work is pushed up and I'll give it a try.

Cool cool cool.  It's going to take me a while longer to polish these commits but you can see my WIP at https://github.com/ncalexan/rust-android-gradle/tree/citest.  It even has the beginning of a test suite with green tests (wild, I know) at https://github.com/ncalexan/rust-android-gradle/actions/runs/802973033.

In terms of help wanted, the matrix of AGP versions and Gradle versions is in https://github.com/ncalexan/rust-android-gradle/blob/citest/plugin/build.gradle#L31.  And there's lots of functionality that we would like to test; this is just the most basic stuff: `cargoBuild` puts a `.so` in a reasonable place.  But the framework for making sure we can do good things as AGP and Gradle evolves is in place.

**Comment by perqin** [comment]
@ncalexan I've pulled your WIP and tested on my project which uses AGP 4.1.3, and it works perfectly!

**Comment by ncalexan** [comment]
This should have been addressed by #60.
